import crypto from 'crypto'
import { ReconciliationProposal } from './types.js'

export interface HumanApprovalRecord {
  approvedBy: string
  approvedAt: string
  approvedProposalHash: string
  approvalToken?: string
}

export interface AuthoritativeProposalRecord {
  proposalId: string
  proposalHash: string
  sourceDocumentHash?: string
  issuedAt: number
  expiresAt: number
  status: 'ISSUED' | 'APPROVED' | 'COMMITTED' | 'REVOKED'
  authorityToken: string
  humanApproval?: HumanApprovalRecord
}

// In-memory authority registry for issued proposals
// Enforces that only proposals generated by executeReconciliationPipeline() are committable.
const authoritativeRegistry = new Map<string, AuthoritativeProposalRecord>()

const SERVER_AUTHORITY_SECRET = process.env.PROPOSAL_AUTHORITY_SECRET || 'projectson_canonical_reconciliation_secret_2026'
const DEFAULT_PROPOSAL_TTL_MS = 3600 * 1000 // 1 hour

/**
 * Register an authoritative proposal produced by the deterministic reconciliation engine.
 * Generates an HMAC authority token bound to proposalId and proposalHash.
 */
export function registerAuthoritativeProposal(
  proposal: ReconciliationProposal,
  ttlMs: number = DEFAULT_PROPOSAL_TTL_MS
): string {
  if (!proposal.proposalId || !proposal.proposalHash) {
    throw new Error('Cannot register proposal: proposalId and proposalHash are required')
  }

  const issuedAt = Date.now()
  const expiresAt = issuedAt + ttlMs

  const authorityToken = crypto
    .createHmac('sha256', SERVER_AUTHORITY_SECRET)
    .update(`${proposal.proposalId}:${proposal.proposalHash}:${issuedAt}`)
    .digest('hex')

  const record: AuthoritativeProposalRecord = {
    proposalId: proposal.proposalId,
    proposalHash: proposal.proposalHash,
    sourceDocumentHash: proposal.sourceDocumentHash,
    issuedAt,
    expiresAt,
    status: 'ISSUED',
    authorityToken
  }

  authoritativeRegistry.set(proposal.proposalId, record)

  // Attach authority token to proposal
  ;(proposal as any).authorityToken = authorityToken

  return authorityToken
}

/**
 * Explicitly record a human approval for an authoritative proposal.
 * Generates a tamper-proof HMAC approval token bound to proposalId, proposalHash, and approver.
 */
export function recordHumanApproval(
  proposalId: string,
  approval: HumanApprovalRecord
): { valid: boolean; approvalToken?: string; error?: string } {
  if (!proposalId) {
    return { valid: false, error: 'PROPOSAL_ID_MISSING: proposalId is required.' }
  }
  if (!approval || !approval.approvedBy || !approval.approvedBy.trim()) {
    return { valid: false, error: 'APPROVER_REQUIRED: approvedBy must be specified for human approval.' }
  }
  if (!approval.approvedProposalHash) {
    return { valid: false, error: 'APPROVAL_HASH_MISSING: approvedProposalHash is required.' }
  }

  const record = authoritativeRegistry.get(proposalId)
  if (!record) {
    return {
      valid: false,
      error: 'UNAUTHORIZED_PROPOSAL_ORIGIN: Cannot approve proposal that was not registered by reconciliation engine.'
    }
  }

  if (record.status === 'COMMITTED') {
    return {
      valid: false,
      error: 'PROPOSAL_ALREADY_COMMITTED: Cannot approve a proposal that has already been committed to database.'
    }
  }

  if (record.status === 'REVOKED') {
    return {
      valid: false,
      error: 'PROPOSAL_REVOKED: Cannot approve a revoked proposal.'
    }
  }

  if (Date.now() > record.expiresAt) {
    return {
      valid: false,
      error: 'PROPOSAL_EXPIRED: Proposal execution TTL has expired. Please re-run alignment.'
    }
  }

  if (approval.approvedProposalHash !== record.proposalHash) {
    return {
      valid: false,
      error: `HASH_MISMATCH_WITH_REGISTERED: Approved proposal hash (${approval.approvedProposalHash}) does not match registered hash (${record.proposalHash}).`
    }
  }

  const approvalToken = crypto
    .createHmac('sha256', SERVER_AUTHORITY_SECRET)
    .update(`${proposalId}:${record.proposalHash}:${approval.approvedBy}:${approval.approvedAt || Date.now()}`)
    .digest('hex')

  record.humanApproval = {
    ...approval,
    approvalToken
  }
  record.status = 'APPROVED'

  return { valid: true, approvalToken }
}

/**
 * Retrieve registered authoritative proposal record.
 */
export function getAuthoritativeProposal(proposalId: string): AuthoritativeProposalRecord | undefined {
  return authoritativeRegistry.get(proposalId)
}

/**
 * Verify whether a given proposal has genuine server-side authority.
 * Rejects forged, client-calculated, replayed, expired, unapproved, or tampered proposals.
 */
export function verifyProposalAuthority(
  proposalId?: string,
  proposalHash?: string,
  authorityToken?: string,
  options?: {
    requireHumanApproval?: boolean
    humanApproval?: HumanApprovalRecord
  }
): { valid: boolean; error?: string } {
  if (!proposalId) {
    return { valid: false, error: 'PROPOSAL_ID_MISSING: proposalId is required for authoritative verification.' }
  }
  if (!proposalHash) {
    return { valid: false, error: 'PROPOSAL_HASH_MISSING: proposalHash is required.' }
  }

  const record = authoritativeRegistry.get(proposalId)
  if (!record) {
    return {
      valid: false,
      error: 'UNAUTHORIZED_PROPOSAL_ORIGIN: Proposal was not issued by the server reconciliation engine (Record not found).'
    }
  }

  if (record.status === 'COMMITTED') {
    return {
      valid: false,
      error: 'PROPOSAL_ALREADY_COMMITTED: Proposal has already been applied to database and cannot be replayed.'
    }
  }

  if (record.status === 'REVOKED') {
    return {
      valid: false,
      error: 'PROPOSAL_REVOKED: Proposal has been revoked.'
    }
  }

  if (Date.now() > record.expiresAt) {
    return {
      valid: false,
      error: 'PROPOSAL_EXPIRED: Proposal execution TTL has expired. Please re-run alignment.'
    }
  }

  if (record.proposalHash !== proposalHash) {
    return {
      valid: false,
      error: `HASH_MISMATCH_WITH_REGISTERED: Submitted payload hash does not match server-issued hash for ${proposalId}.`
    }
  }

  if (authorityToken && authorityToken !== record.authorityToken) {
    return {
      valid: false,
      error: 'INVALID_AUTHORITY_TOKEN: Authority token does not match server-issued record.'
    }
  }

  // Phase 3A: Enforce Human Approval Gate
  if (options?.requireHumanApproval) {
    const approval = options.humanApproval || record.humanApproval
    if (!approval || !approval.approvedBy || !approval.approvedBy.trim()) {
      return {
        valid: false,
        error: 'HUMAN_APPROVAL_REQUIRED: No AI-originated proposal may be applied without explicit human approval.'
      }
    }

    if (approval.approvedProposalHash !== record.proposalHash) {
      return {
        valid: false,
        error: `APPROVAL_HASH_MISMATCH: Human approval referenced hash (${approval.approvedProposalHash}) does not match current proposal hash (${record.proposalHash}).`
      }
    }

    if (record.humanApproval?.approvalToken && approval.approvalToken && approval.approvalToken !== record.humanApproval.approvalToken) {
      return {
        valid: false,
        error: 'INVALID_APPROVAL_TOKEN: Human approval token does not match server-recorded approval.'
      }
    }
  }

  return { valid: true }
}

/**
 * Mark a proposal as successfully committed to the database.
 * Prevents replay attacks.
 */
export function markProposalCommitted(proposalId: string): void {
  const record = authoritativeRegistry.get(proposalId)
  if (record) {
    record.status = 'COMMITTED'
  }
}

/**
 * Clear registry (useful for test isolation)
 */
export function clearProposalRegistry(): void {
  authoritativeRegistry.clear()
}
